### ISSUE TITLE
Use fastmatter over yaml-front-matter?

### ISSUE THREAD

**Issue by bebraw** [eldh/yaml-frontmatter-loader#2]
I think [fastmatter](https://www.npmjs.com/package/fastmatter) should be faster. If you can hook me up with the repo and npm, I can manage the upgrade (literally a couple of lines).

**Comment by eldh** [comment]
Should be all set now, let me know if something's not working!

**Comment by bebraw** [comment]
Looks good.

Maybe it would be nice to move this below **webpack-contrib** org. This is enough for me at the moment, though. 👍

**Comment by eldh** [comment]
yeah I wouldn't mind moving it. I need to have access to create repos there right? Or there another way?

**Comment by bebraw** [comment]
If you add me as an admin to this repo, I can move over.

**Comment by eldh** [comment]
Hm, not sure I can do that, but I can transfer it to you though.

**Comment by eldh** [comment]
otoh, if it's a lot of trouble I can maintain this here.

**Comment by bebraw** [comment]
I added you as a member to the org so you should be able to move the repo over now. I forgot GitHub gives little control over individual repos like this.

**Comment by bebraw** [comment]
Done, thanks. 👍

**Comment by eldh** [comment]
sweet :)

**Comment by shellscape** [comment]
Looks like this one is a wrap
