### ISSUE TITLE
Standardize README

### ISSUE THREAD

**Issue by michael-ciniawsky** [eldh/yaml-frontmatter-loader#5]

**Comment by skipjack** [comment]
Just a heads up, the readme title looks like it got auto-corrected:

![image](https://cloud.githubusercontent.com/assets/8988697/25829966/af3e9aba-3427-11e7-8508-d3f51e21b82f.png)

**Comment by michael-ciniawsky** [comment]
😆  Oh jeeez.. I take this one as the first one later or send a quick PR 🙃 😛
